name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
    tags: ["v*"]
  pull_request:
    branches: ["main", "master"]

permissions: {}

jobs:
  build-with-xk6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: false
      - name: Setup xk6
        uses: grafana/setup-xk6@v1.0.0
        with:
          xk6-version: "0.19.2"
      - name: Build
        run: make build
      - name: Test
        run: make test
